name: vit_cache
description: A Dart package for caching single values and multiple key-value pairs with a time-to-live (TTL) mechanism.
version: 2.1.1
repository: https://github.com/TimeLord2010/vit_cache

environment:
  sdk: ^3.6.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
